---
- name: Add monit scripts
  copy: src={{ item }} dest=/usr/local/bin/ owner=root group=root mode=0755
  with_items:
  - dns_cv.sh
  - dns_msdcs.sh
  - dns_pf.sh
- name: Add monit tests
  copy: src={{ item }} dest=/etc/monit/conf.d/ owner=root group=root mode=0644
  with_items:
  - dns_tests
  - ping_tests
  notify:
  - monit
- name: Add monit site
  copy: src=site dest=/etc/apache2/sites-available/monit owner=root group=root mode=0644
  notify:
  - apache2
- name: Enable monit site
  file: src=../sites-available/monit dest=/etc/apache2/sites-enabled/monit state=link owner=root group=root
  notify:
  - apache2
- name: Enable needed apache2 mods
  file: src=../mods-available/{{ item }} dest=/etc/apache2/mods-enabled/{{ item }} state=link owner=root group=root
  with_items:
  - proxy.conf
  - proxy.load
  - proxy_http.load
  notify:
  - apache2
