---
- name: Configure firewall
  copy: src=nslcd.rules dest=/etc/iptables.d/
  notify:
  - iptables
- name: Install libpam-ldapd and zsh
  apt: name={{ item }} state=present
  with_items:
  - libpam-ldapd
  - zsh
- name: Stop nscd
  service: name=nscd state=stopped enabled=no
- name: Configure libpam-ldapd
  template: src=nslcd.conf dest=/etc/nslcd.conf owner=root group=nslcd mode=0640
- name: Add ldap to nsswitch
  lineinfile: "dest=/etc/nsswitch.conf regexp='^{{ item }}:' insertafter=regex line='{{ item }}:         files ldap'"
  with_items:
  - passwd
  - group
  - shadow
- name: Install python-pycurl for apt_repository
  apt: pkg=python-pycurl state=present
- name: Add backports
  apt_repository: repo="deb http://ftp.utexas.edu/debian wheezy-backports main" update_cache=yes
- name: Install openssh-server from backports
  apt: pkg=openssh-server default_release=wheezy-backports state=latest # Must use latest here to override the server installed in base
- name: Add authorizedkeyscommand user
  user: name=autorizedkeyscommand createhome=no groups= shell=/bin/false system=yes state=present
- name: Fix /usr/local permissions
  file: path=/usr/local mode=0555 state=directory
- name: Add AuthorizedKeysCommand script
  copy: src=ssh_pubkeys dest=/usr/local/sbin/ssh_pubkeys owner=root group=root mode=0755
- name: Require pubkey and password
  lineinfile: dest=/etc/ssh/sshd_config state=present line='{{ item }}'
  with_items:
  - 'AuthorizedKeysCommandUser authorizedkeyscommand'
  - 'AuthorizedKeysCommand /usr/local/sbin/ssh_pubkeys'
  - 'AuthenticationMethods publickey,password'
- name: Add Match for internal users
  lineinfile: dest=/etc/ssh/sshd_config state=present line='Match Address 192.168.42.0/24'
  notify:
  - sshd
- name: Make intenal need only password
  lineinfile: dest=/etc/ssh/sshd_config state=present insertafter='Match Address 192.168.42.0/24' line='  AuthenticationMethods password'
