---
account_admin_username: "{{ lookup('file', 'secret/account_admin_username') }}"
account_admin_password: "{{ lookup('file', 'secret/account_admin_password') }}"
account_salt: "{{ lookup('file', 'secret/account_salt') }}"
