---
- name: netstart
  command: sh /etc/netstart {{ internal_if }} {{ external_if }} {{ pf_if }} carp0 carp1 carp2
- name: dhcpd
  command: /etc/rc.d/dhcpd restart
- name: ntpd
  command: /etc/rc.d/ntpd restart
- name: nsd
  command: nsd-control reconfig
- name: unbound
  command: unbound-control reload
- name: pf
  command: pfctl -f /etc/pf.conf
