---
- name: netstart
  command: sh /etc/netstart
- name: dhcpd
  command: /etc/rc.d/dhcpd restart
- name: ntpd
  command: /etc/rc.d/ntpd restart
- name: restart named
  command: /etc/rc.d/named restart
- name: reload named
  command: rndc reload
- name: pf
  command: pfctl -f /etc/pf.conf
