---
- name: Add SSH banner
  copy: src=ssh_banner dest=/etc/ssh/banner
- name: Enable SSH banner
  lineinfile: dest=/etc/ssh/sshd_config state=present line='Banner /etc/ssh/banner'
  notify:
  - sshd
