---
- name: Configure firewall for ssh-box
  copy: src=ssh-box.rules dest=/etc/iptables.d/ssh-box.rules owner=root group=root mode=0644
  notify:
  - iptables
- name: Install ssh-box packages
  apt: pkg={{ item }} state=present
  with_items:
  - zsh
  - irssi
  - weechat
  - mosh
  - screen
  - tmux
  # For SASL in irssi
  - libcrypt-blowfish-perl
  - libcrypt-dh-perl
  - libcrypt-openssl-bignum-perl
  # For jabber in weechat
  - python-xmpp
