---
- name: Configure monit for account site
  copy: src=monit dest=/etc/monit/web.d/account
  notify:
  - monit
- name: Copy account files
  copy: src=account dest=/var/www/sites/
- name: Copy config files
  copy: src=secret/config dest=/var/www/sites/account/
- name: Add account sites
  copy: src={{ item }}.site dest=/etc/apache2/sites-available/{{ item }}
  with_items:
  - account
  - accounts
  notify:
  - apache2
- name: Enable account sites
  file: src=../sites-available/{{ item }} dest=/etc/apache2/sites-enabled/{{ item }} state=link
  with_items:
  - account
  - accounts
  notify:
  - apache2
