---
- name: Install wakeonlan
  apt: pkg=wakeonlan state=present
- name: Configure firewall for wakeonlan
  copy: src=wakeonlan.rules dest=/etc/iptables.d/wakeonlan.rules owner=root group=root mode=0644
  notify:
  - iptables
- name: Add MAC address list
  copy: src=cv_mac_addr dest=/etc/cv_mac_addr owner=root group=root mode=0644
- name: Add wakecv script
  copy: src=wakecv dest=/usr/local/bin/wakecv owner=root group=root mode=0755
