---
- name: Install wakeonlan
  apt: pkg=wakeonlan state=present
- name: Configure firewall for wakeonlan
  copy: src=wakeonlan.rules dest=/etc/iptables.d/
  notify:
  - iptables
- name: Add MAC address list
  copy: src=cv_mac_addr dest=/etc
- name: Add wakecv script
  copy: src=wakecv dest=/usr/local/bin/
