---
- name: Install xbmc
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
  - xinit
  - xbmc

- name: Add xbmc user
  user: name=xbmc state=present

- name: Replace inittab for startup
  lineinfile: dest=/etc/inittab insertafter=EOF line='7:23:wait:su xbmc -c "xinit /usr/bin/xbmc --standalone -- :0"'
