---
- name: Configure monit for newsletter site
  copy: src=monit dest=/etc/monit/web.d/newsletter owner=root group=root mode=0644
  notify:
  - monit
- name: Copy newletter files
  copy: src=newsletter dest=/var/www/sites/ owner=root group=root mode=0755
- name: Add newsletters sites
  copy: src={{ item }}.site dest=/etc/apache2/sites-available/{{ item }} owner=root group=root mode=0644
  with_items:
  - newsletter
  - newsletters
  notify:
  - apache2
- name: Enable newsletter sites
  file: src=../sites-available/{{ item }} dest=/etc/apache2/sites-enabled/{{ item }} state=link owner=root group=root
  with_items:
  - newsletter
  - newsletters
  notify:
  - apache2
