---
- name: Copy hostname files
  template: src={{ item }} dest=/etc/ owner=root group=wheel mode=0640
  with_items:
  - etc/hostname.carp0
  - etc/hostname.carp1
  - etc/hostname.carp2
  - etc/hostname.pfsync0
  notify:
  - netstart
- name: Copy internal hostname file
  template: src=etc/hostname.bge1 dest=/etc/hostname.{{ internal_if }} owner=root group=wheel mode=0640
  notify:
  - netstart
- name: Copy external hostname file
  template: src=etc/hostname.bge0 dest=/etc/hostname.{{ external_if }} owner=root group=wheel mode=0640
  notify:
  - netstart
- name: Copy pfsync hostname file
  template: src=etc/hostname.em0 dest=/etc/hostname.{{ pf_if }} owner=root group=wheel mode=0640
  notify:
  - netstart
- name: Copy mygate file
  template: src=etc/mygate dest=/etc/mygate owner=root group=wheel mode=0640
  notify:
  - netstart

- name: Copy firewall
  template: src=etc/pf.conf dest=/etc/pf.conf owner=root group=wheel mode=0600
  notify:
  - pf
- name: Install isc-dhcpd
  openbsd_pkg: name=isc-dhcp-server state=present
  environment:
    PKG_PATH: "{{ PKG_PATH }}"
- name: Copy dhcpd config
  template: src=etc/dhcpd.conf dest=/etc/dhcpd.conf owner=root group=wheel mode=0644
  notify:
  -  dhcpd
- name: Copy ntpd config
  template: src=etc/ntpd.conf dest=/etc/ntpd.conf owner=root group=wheel mode=0644
  notify:
  - ntpd
- name: Copy rc.conf.local
  template: src=etc/rc.conf.local dest=/etc/rc.conf.local owner=root group=wheel mode=0644
- name: Copy common config
  copy: src={{ item }} dest=/{{ item }} owner=root group=wheel mode=0644
  with_items:
  - etc/pkg.conf
  - etc/rc.local
  - etc/rc.securelevel
  - etc/resolv.conf.boot
  - etc/resolv.conf.final
  - etc/sysctl.conf

- name: Copy rc.d scripts
  copy: src={{ item }} dest=/{{ item }} owner=root group=wheel mode=0555
  with_items:
  - etc/rc.d/dhcpd dest=/etc/rc.d/dhcpd

- name: Generate rndc keys
  command: rndc-confgen -at /var/named creates=/etc/rndc.key
  notify:
  - restart named
- name: Fix permissions of rndc key
  file: path=/var/named/etc/rndc.key owner=root group=named mode=0640
- name: Copy named config
  template: src=var/named/etc/named.conf dest=/var/named/etc/named.conf owner=root group=named mode=0640
  notify:
  - reload named
- name: Add UTD forwarders
  copy: src=var/named/etc/UTDNS dest=/var/named/etc/UTDNS owner=root group=named mode=0640
  notify:
  - reload named
- name: Add dummy zones
  copy: src=var/named/master/{{ item }} dest=/var/named/master/{{ item }} owner=root group=wheel mode=0644
  with_items:
  - db.0
  - db.255
  notify:
  - reload named
