---
- name: Copy hostname files
  template: src={{ item }} dest=/etc/ mode=0644
  with_items:
  - etc/hostname.bge0
  - etc/hostname.bge1
  - etc/hostname.carp0
  - etc/hostname.carp1
  - etc/hostname.carp2
  - etc/hostname.em0
  - etc/hostname.pfsync0
  notify:
  - netstart
- name: Copy firewall
  copy: src=etc/pf.conf dest=/etc/pf.conf mode=0600
  notify:
  - pf
- name: Copy dhcpd config
  template: src=etc/dhcpd.conf dest=/etc/dhcpd.conf mode=0644
  notify:
  -  dhcpd
- name: Copy dhclient config
  template: src=etc/dhclient.conf dest=/etc/dhclient.conf mode=0644
- name: Copy ntpd config
  template: src=etc/ntpd.conf dest=/etc/ntpd.conf mode=0644
  notify:
  - ntpd
- name: Copy common config
  copy: src={{ item }} dest=/{{ item }} mode=0644
  with_items:
  - etc/mygate
  - etc/rc.conf.local
  - etc/rc.local
  - etc/rc.securelevel
  - etc/resolv.conf.final
  - etc/sysctl.conf

- name: Copy rc.d scripts
  copy: src={{ item }} dest=/{{ item }}
  with_items:
  - etc/rc.d/dhcpd dest=/etc/rc.d/dhcpd
  - etc/rc.d/update_pf_minecraft
  - etc/rc.d/update_utdns

- name: Copy named config
  template: src=var/named/etc/named.conf dest=/var/named/etc/named.conf mode=0644
  notify:
  - named
- name: Add UTD forwarders
  copy: src=var/named/etc/UTDNS dest=/var/named/etc/UTDNS
  notify:
  - named
- name: Add dummy zones
  copy: src=var/named/master/{{ item }} dest=/var/named/master/{{ item }} mode=0644
  with_items:
  - db.0
  - db.255
  notify:
  - named
