---
- name: Copy hostname files
  template: src={{ item }} dest=/etc/ mode=0644
  with_items:
  - etc/hostname.bge0
  - etc/hostname.bge1
  - etc/hostname.carp0
  - etc/hostname.carp1
  - etc/hostname.carp2
  - etc/hostname.em0
  - etc/hostname.pfsync0
  notify:
  - netstart
- name: Copy dhcpd config
  template: src=etc/dhcpd.conf dest=/etc/dhcpd.conf mode=0644
  notify:
  -  dhcpd
- name: Copy dhclient config
  template: src=etc/dhclient.conf dest=/etc/dhclient.conf mode=0644
- name: Copy ntpd config
  template: src=etc/ntpd.conf dest=/etc/ntpd.conf mode=0644
  notify:
  - ntpd
- name: Copy named config
  template: src=var/named/etc/named.conf dest=/var/named/etc/named.conf mode=0644
  notify:
  - named
- name: Copy firewall
  copy: src=etc/pf.conf dest=/etc/pf.conf mode=0600
  notify:
  - pf
- copy: src=etc/mygate dest=/etc/mygate mode=0644

- copy: src=etc/rc.conf.local dest=/etc/rc.conf.local mode=0644
- copy: src=etc/rc.local dest=/etc/rc.local mode=0644
- copy: src=etc/rc.securelevel dest=/etc/rc.securelevel mode=0644
- copy: src=etc/resolv.conf.final dest=/etc/resolv.conf.final mode=0644
- copy: src=etc/sysctl.conf dest=/etc/sysctl.conf mode=0644

- copy: src=etc/rc.d/dhcpd dest=/etc/rc.d/dhcpd
- copy: src=etc/rc.d/update_pf_minecraft dest=/etc/rc.d/update_pf_minecraft
- copy: src=etc/rc.d/update_utdns dest=/etc/rc.d/update_utdns

- copy: src=var/named/etc/UTDNS dest=/var/named/etc/UTDNS

- copy: src=var/named/master/db.0 dest=/var/named/master/db.0 mode=0644
- copy: src=var/named/master/db.255 dest=/var/named/master/db.255 mode=0644
