---
- name: Add master zones
  copy: src=var/named/master/{{ item }} dest=/var/named/master/{{ item }} owner=root group=wheel mode=0644
  with_items:
  - collegiumv.org
  - db.192.168.42
  - sunray-servers
  notify:
  - named

# TODO: Add cron job
